export default {
  GLOBAL_REQUEST: 'GLOBAL_REQUEST',
  GLOBAL_SUCCESS: 'GLOBAL_SUCCESS',
  GLOBAL_ERROR: 'GLOBAL_ERROR',
  ADD_DATA: 'ADD_DATA',
  UPDATE_DATA: 'UPDATE_DATA',
  DELETE_DATA: 'DELETE_DATA',
  SET_STATE: 'SET_STATE'
};