export const SET_ACCOUNT = 'SET_ACCOUNT';
export const SET_ACCOUNT_ITEM = 'SET_ACCOUNT_ITEM';
export const EMPTY_ACCOUNT = 'EMPTY_ACCOUNT';
export const ADD_ACCOUNT_ITEM = 'ADD_ACCOUNT_ITEM';
export const ADD_ACCOUNT_ITEM_AFTER = 'ADD_ACCOUNT_ITEM_AFTER';
export const DELETE_ACCOUNT_ITEM = 'DELETE_ACCOUNT_ITEM';

export default {
  SET_ACCOUNT,
  SET_ACCOUNT_ITEM,
  EMPTY_ACCOUNT,
  ADD_ACCOUNT_ITEM,
  ADD_ACCOUNT_ITEM_AFTER,
  DELETE_ACCOUNT_ITEM
}
